### ISSUE TITLE
Encoding from Opencv mat to buffers image error 

### ISSUE THREAD

**Issue by dagata-mining** [Jetraw/Jetraw#6] opened 2023-09-29 02:34 UTC
I'm trying to implement an encoding in CPP with open CV. But I keep getting the 17 status code. 

First I call this function to initialize 

```cpp
bool initialize(std::string calibration, std::string license)
    {
        if (jetraw_tiff_init()  != 0) return false;
        dpcore_set_loglevel(2);
        jetraw_tiff_set_loglevel(2);
        /* Passing in an empty string will
        * make Jetraw look in the default
        * path in which the license is located. */
        if (jetraw_tiff_set_license(license.c_str()) != 0) return false;

        /* Load calibration.dat */
        if (dpcore_load_parameters(calibration.c_str()) !=0) return false;

        return true;
    }

```

Then to encode im using this with a 8UC1 Mat  that I imported from the this raw.tiff image 
 
```cpp

bool encode(const cv::Mat &in, int rows, int cols, const char* &dst)
    {
        int32_t dstLen = cols * rows /2;
        std::unique_ptr<char[]> dstBuffer(new char[dstLen]);
        uint16_t* inputBuffer = reinterpret_cast<uint16_t*>(in.data);
       int value = dpcore_embed_meta(inputBuffer, cols * rows, "002KK");
        int value = jetraw_encode(inputBuffer,cols, rows,dstBuffer.get(),&dstLen);
        if( value == 0)
        {
            //Success in encoding
            std::unique_ptr<char[]> croppedDstBuffer(new char[dstLen]);
            std::memcpy(croppedDstBuffer.get(), dstBuffer.get(), dstLen); // Copy data
            dst = croppedDstBuffer.get();
            std::cout << "Compressed from " << cols * rows << " to " << dstLen << " (" << (float)(cols * rows)/(float)dstLen
            << "x times)" << std::endl;
           return true;
        }
        return false;
    }
 
```

Then to decode I'm using this

```cpp
  bool decode(const std::vector<uchar> &dataIn, int rows, int cols, cv::Mat &out)
    {
        int pixels = rows * cols;
        int size = dataIn.size();
        uint16_t *imageBuffer;
        const char* pSrcBuffer = reinterpret_cast<const char*>(dataIn.data());
        //std::unique_ptr<uint16_t[]> imageBuffer(new uint16_t[pixels]);
        if (jetraw_decode(pSrcBuffer, size, imageBuffer, pixels)==0)
        {
            cv::Mat mat(rows, cols, CV_16UC3, imageBuffer);
            mat.convertTo(out, CV_8UC3);
            return true;
        }
        else return false;
    }
```
Note that I'm using a TIFF as a debug/implementation step, but will be dealing with buffers directly when implementing with my ros node. I've also added the calibration
[raw.zip](https://github.com/Jetraw/Jetraw/files/12755809/raw.zip)

**Comment by moliva-newb** [comment] 2023-10-02 09:07
Hello @dagata-mining 

I will create a working code snippet with 8-bit input buffers and share it with you. 

Can you let me know what opencv version you are using? And operating system, please? 

Thank you!

**Comment by dagata-mining** [comment] 2023-10-02 11:49
We are using opencv 4.2.0 with ubuntu 20.04. Note that I managed to run the compress workflow with command line (dpcore and jetrawtiff) but the compressed image was the same size (
```bash
$./dpcore -d ../../Documents/compress/ -i 002KK ../../Documents/raw_5.tiff -v debug -p /home/alex/third_party/Odometry/tests/data/uncompress/002kk.dat -c
```
 And when doing the 
```cpp
dpcore_embed_meta(inputBuffer, cols * rows, "002KK");
``` 
Im getting a 8 as dpstatus, which is weird because it is working with the command line worflow

**Comment by moliva-newb** [comment] 2023-10-02 14:54
Hello again, 

Thanks for your answer. 

Using the CLI with an 8-bit image will return the original image with no modification because we do not support 8-bit images. The behavior you see is the expected one. 

Regarding the `dp_status` return value of 8, it means `unknown_identifier`, meaning that the .dat file was not well registered or something is wrong with it. 

In Linux you should add your .dat file in the following folder, so it will be automatically found:
`~/.config/dpcore/`

and your license file (`license.txt`) in:
`~/.config/jetraw/`

Then simply calling `dpcore_init()`, your calibration ids will be directly accessible and your license ready to be used within the code. 

Tomorrow I will send you the code using our API to be able to compress 8-bit images, as it cannot be done with the CLI at the moment. 

Best,

**Comment by dagata-mining** [comment] 2023-10-02 15:04
Thanks, 
For the identifier I've added the .dat calibration file if you can check if you can load the parameters:
dpcore_load_parameters(calibration.c_str()) through cpp api

**Comment by moliva-newb** [comment] 2023-10-03 13:33
Hello again @dagata-mining 

Yes, I can load them with no problems but the loading parameters step is not necessary if you add the .dat file in the `config` folder mentioned before. In any case I have added a note if you want to load it manually, but I suggest to use the `dpcore_init()` mechanism instead, if possible.

The attached code snippet is working using your 8-bit input image and saving an 8-bit image as output (only 1 channel, in your script you wanted to save it with 3 channels, it can be changed to whatever you want).

Attached in the .zip file you will find: 
- Original image (raw.tiff) 
- Decompressed image (decompressed.tiff)
- New .dat file with an 8-bit saturation level (002kk-8bits.dat). The .dat file  you currently have is for 12-bit camera. The other calibration values need to be adapted to 8-bit as well but we need to contact the camera manufacturer first. Meanwhile for your integration tests you can use the attached .dat file if you intend to use 8-bit images. Note that the calibration id has been modified to `002KK_8bits`. 
- Code snippet. 

Let me know if you have any doubts about the code. 

Enjoy! 
[code_snippet_8bit_buffers.zip](https://github.com/Jetraw/Jetraw/files/12793011/code_snippet_8bit_buffers.zip)

**Comment by dagata-mining** [comment] 2023-10-04 20:58
I've tried a few things but its still not working. Which version are you using? I'm using  the precompiled one 
and  the does not exists 
#include <jetraw/logging/logging.hpp>

**Comment by arvequina** [comment] 2023-10-04 23:22
Hi, what error do you have? 

The logging include is not really necessary. I was using the development environment of the latest release 22.02.16.1 but I can also try just using the dynamic libraries as a dependency, in principle it should not change anything. 

Could you please share your whole code? Like that I can compile it and try to make it work on my machine, so we are sure to be on the same page. 

Thanks for your message!

**Comment by dagata-mining** [comment] 2023-10-05 15:00
Hi @arvequina,
So I ran it stand alone  and it is working, so the problem came from our  other full stack (had som weird behaviour) so I deleted the whole build directory and built from scratch and it did work... 

So any one wondering and having the same issue I've added my project .zip and here's the cmakelists.txt I used. Note that my .dat file is in the ~/.config/dpcore and my license is in ~/.config/jetraw directories
```cmake
cmake_minimum_required(VERSION 3.26)
project(jetrawtest)

set(CMAKE_CXX_STANDARD 14)
set(JETRAW_INCLUDE_DIR " ${CMAKE_CURRENT_SOURCE_DIR}/JetrawWithDPCore-22.02.16.1/include")

set (JETRAW_LIBS
        ${CMAKE_CURRENT_SOURCE_DIR}/JetrawWithDPCore-22.02.16.1/lib/libcrypto.so.1.1
        ${CMAKE_CURRENT_SOURCE_DIR}/JetrawWithDPCore-22.02.16.1/lib/libdpcore.so
        ${CMAKE_CURRENT_SOURCE_DIR}/JetrawWithDPCore-22.02.16.1/lib/libjetraw.so
        ${CMAKE_CURRENT_SOURCE_DIR}/JetrawWithDPCore-22.02.16.1/lib/libjetraw_tiff.so
        ${CMAKE_CURRENT_SOURCE_DIR}/JetrawWithDPCore-22.02.16.1/lib/libssl.so.1.1)
find_package( OpenCV REQUIRED )


# Specify the include directory for the library
include_directories(${JETRAW_INCLUDE_DIR}
)

include_directories(${OpenCV_INCLUDE_DIRS})
LINK_DIRECTORIES(
        ${OpenCV_LIBRARY_DIRS}
)

add_executable(jetrawtest main.cpp)
target_link_libraries(jetrawtest ${JETRAW_LIBS} ${OpenCV_LIBS})
```

[jetrawtest.zip](https://github.com/Jetraw/Jetraw/files/12819930/jetrawtest.zip)

**Comment by dagata-mining** [comment] 2023-10-05 15:43
Does the dpcore_init() caches something in the build files? Because if I run it once it works but then, if the pipeline does not complete, the next time I run, I get weird data moving errors... do I need to close/delete pointers something in order to prevent that from happening?

**Comment by moliva-newb** [comment] 2023-10-05 15:56
Hi @dagata-mining glad to made it work and for sharing your CMakeList file. 

Regarding `dpcore_init()` the only thing it does is to create a registry with all the camera identifiers found in the system from the .dat files and to detect the license file. 

Can you show me how your pipeline works? Data management can be tricky if you do several things at the same time or launching it before it has finished the first iteration. Maybe some pointers after the first run are pointing to wrong places? I cannot say much without seeing the exact example. 

Thanks!

**Comment by arvequina** [comment] 2023-10-05 16:01
Hi @dagata-mining glad you made it work and for sharing your CMakeList file.

Regarding `dpcore_init()` the only thing it does is to create a registry with all the camera identifiers found in the system from the .dat files and to detect the license file.

Can you show me how your pipeline works? Data management can be tricky if you do several things at the same time or launching it before it has finished the first iteration. Maybe some pointers after the first run are pointing to wrong places? I cannot say much without seeing the exact example.

Thanks!

**Comment by dagata-mining** [comment] 2023-10-05 16:07
Hi so when trying to encode, I'm getting a memory allocation failure (dp_status = 1). Here's the coomplete pipeline, I'm using yaml-cpp to parse some information

function test
```cpp
struct ImageReadingTest: testing::Test, testing::WithParamInterface<test_params>
{
    bool running;

    ImageReadingTest()
    {
        running = true;
        std::string filepath = GetParam().testYamlFilePath;

        YAML::Node config = YAML::LoadFile(filepath);

        std::string export_file;
        std::string topic_name;
        std::string project_path;
        std::string bag_name;
        std::string raw_name;
        std::string bag_path;
        std::string raw_path;


        // Parse project_path
        if (!config["project_path"].IsDefined())
        {
            throw util::ParseException("project_path does not exist in yaml file");
        }
        project_path = config["project_path"].as<std::string>();

        // Parse bag_name
        if (!config["bag_name"].IsDefined())
        {
            throw util::ParseException("bag_name does not exist in yaml file");
        }
        bag_name = config["bag_name"].as<std::string>();

        // Parse bag_name
        if (!config["raw_name"].IsDefined())
        {
            throw util::ParseException("raw_name does not exist in yaml file");
        }
        raw_name = config["raw_name"].as<std::string>();

        raw_path = project_path + raw_name;


        // Parse topic_name
        if (!config["topic_uncompress_img_name"].IsDefined())
        {
            throw util::ParseException("Topic to uncompressed not defined. Test aborted");
            return;
        }
        topic_name = config["topic_uncompress_img_name"].as<std::string>();

        // Rest of the code using bagFile and exportFile
        auto core = dpcore_init();

        cv::Mat inputImage = cv::imread(raw_path, cv::IMREAD_UNCHANGED);
        if (inputImage.empty()) {
            std::cerr << "[ERROR] input image empty" << std::endl;
            running = false;
            return;
        }
        int32_t dstLen = 0;
        const char* encodedData = nullptr;
        if (!jetrawCompress::encode(inputImage,encodedData,dstLen))
        {
            std::cerr << "[ERROR] encoding failed!" << std::endl;
            running =  false;
            return;
        }
        cv::Mat decodedImage;
        if (!jetrawCompress::decode(encodedData, inputImage.rows, inputImage.cols, decodedImage,
                    dstLen)) {
            std::cerr << "[ERROR] decoding failed!" << std::endl;
            running =  false;
            return;
        }
        std::string outFile = project_path + "decompressed.tiff";
        cv::imwrite(outFile, decodedImage);
        
//        
    }

    ~ImageReadingTest()
    {
        running = false;
    }
};
```




encode function
```cpp
bool encode(const cv::Mat& input,char*& dst, int32_t& dstLen) {
    int rows = input.rows;
    int cols = input.cols;
    dstLen = cols * rows * 0.5;
    // Convert to 16-bit cv::Mat
    cv::Mat mat16bit;
    input.convertTo(mat16bit, CV_16U);
    // Create a unique_ptr for the destination buffer
    std::unique_ptr<char[]> dstBuffer(new char[dstLen]);
    uint16_t* srcBuffer = mat16bit.ptr<uint16_t>();
    // Embed dpcore header
    if (int status = dpcore_embed_meta(srcBuffer, cols * rows, "002KK_8bits") !=
        dp_success) {
        std::cerr << "[ERROR] error while embedding data: " << status
                  << std::endl;
        return false;
    }
    // Encode input buffer
    if (int status = jetraw_encode(srcBuffer, cols, rows, dstBuffer.get(),
                                   &dstLen) != dp_success) {
        std::cerr << "[ERROR] error while encoding data: " << status
                  << std::endl;
        return false;
    }
    std::unique_ptr<char[]> croppedDstBuffer(new char[dstLen]);
    std::memcpy(croppedDstBuffer.get(), dstBuffer.get(), dstLen);
    dst = croppedDstBuffer.release();
    std::cerr << "[INFO] compressed from " << cols * rows << " to " << dstLen
              << " (" << static_cast<float>(cols * rows) / dstLen << "x times)"
              << std::endl;
    return true;
}
```

**Comment by dagata-mining** [comment] 2023-10-05 16:25
Tried to reproduce it with different files and it did work... Might be coming from my  google tests formats...

**Comment by dagata-mining** [comment] 2023-10-05 21:11
So I found out my yaml-cpp library seems to be conflicting

**Comment by dagata-mining** [comment] 2023-10-05 23:06
What flag is used for compiling your binaries? is -march=native enabled as this often leads to these king of problems on our side

**Comment by dagata-mining** [comment] 2023-10-07 16:03
Hi @arvequina ,

Might I have found a potential work around and I'd like to have your opnion.

Currently we are recording our images through a ros-node. This node does not seem to be causing many issues for now. So in the node we are compressing the incoming bayer8 buffers into dpcore buffers,.
 The part where we are having issues is when uncompressing the images in our post-treatment cpp app. That's when the conflict happens between YAML-CPP  and DPcore. So what I'll do (which is not optimal) is I'll serialize the buffer into a temp file, build a custom cpp dpcore/opencv/desrializer app that will uncompress and save the image as a tiff and I'll import it back into my post-treatment app. 
 
 Now based on that, what serializer/deserializer could I use so that it will not conflict with dpcore? Thanks again

**Comment by arvequina** [comment] 2023-10-08 14:08
Hi @dagata-mining, 

Sorry for my late reply. It is quite surprising to have issues with the deserialization, but it is true that we also use yaml-cpp for that purpose and it might have some unknown issues. An alternative would be that you use or another library on your side, for example [rapidyaml](https://github.com/biojppm/rapidyaml) or to use jsons instead [rapidjson](https://miloyip.github.io/rapidjson/). With that you could have a better understanding if the problem is what you are guessing, conflicts with our yaml library. 

The memory allocation issue that were mentioning before it can only come from a null input buffer, but it does not look like because you are passing the cv::Mat directly in the encoding step and in the decoding step you are transferring the ownership to the `dst` buffer when you call `release()` as well so I do not see a problem in there. Then the other option is what you were suggesting, conflicts with the yaml-cpp part when calling `dpcore_embed_meta`. If using another yaml library or using json instead solves the issue, we will definitely know that this is the problem. What I do not get how they can enter in a conflict...

Thanks for sharing and let's keep in touch!

**Comment by dagata-mining** [comment] 2023-10-10 21:29
Thanks fo the info, I'll try a few approaches. Which version of yaml-cpp are you using?

**Comment by arvequina** [comment] 2023-10-11 13:31
Ok, we are using `yaml-cpp-0.6.3`

**Closed** 2023-11-06 10:15 UTC
